readonly -f include
readonly -f install::error
readonly -f install::zinstall
readonly -f install::zparser
readonly -f install::androidCheck
readonly -f install::installer
readonly -f install::prepdir
readonly -f install::installer
readonly -f install::checker